In [5]:
import torch
import torch.utils.data
import torchvision.models
import numpy as np

In [3]:
# torch.mm
arr1 = torch.rand(4,3)
arr2 = torch.randn(3,4)
print(torch.mm(arr1, arr2))

tensor([[ 1.6701,  1.0496,  0.7903, -0.1860],
        [ 1.4751,  0.5480,  1.3900,  0.1419],
        [ 1.0953,  0.4136,  0.4657, -1.0812],
        [ 2.4708,  1.4953,  1.4954,  0.2431]])


In [4]:
# torch.cat
arr1 = torch.rand(1,2,3,4)
arr2 = torch.rand(2,2,3,4)
arr3 = torch.rand(3,2,3,4)
arr4 = torch.rand(4,2,3,4)
output = torch.cat([arr1, arr2, arr3, arr4], 0)
print(output.size())

torch.Size([10, 2, 3, 4])


In [7]:
# torch.max
arr = torch.rand(5,3)
maxvalue, index = torch.max(arr, 1)
print(maxvalue)
print(index)

tensor([ 0.9050,  0.6789,  0.7793,  0.8103,  0.7558])
tensor([ 2,  2,  0,  0,  2])


In [14]:
# adjust learning_rate
learning_rate = 1e-4
new_learning_rate = 1e-5
model = torchvision.models.resnet18()
optimizer = torch.optim.SGD(params=model.parameters(), lr=learning_rate)
for param_group in optimizer.param_groups:
    param_group['lr'] = new_learning_rate